title: Wired Brain Coffee
logo: "/images/company-logo.png?raw=true"
description: >
  first description
  <br><br>
  60 State Street
  Suite 800
  Boston, MA 02109
  <br><br>
  <a href="https://www.pluralsight.com">www.wiredbraincoffee.com</a>

theme: jekyll-theme-minimal
